name: Check code quality
run-name: ${{ github.actor }} pushed to dev

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

jobs:

  quality:
    runs-on: ubuntu-latest
    name: Check format and lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v1
        with:
          version: latest
      - name: Run Biome
        run: biome ci .